# Generated by Django 3.0.8 on 2020-07-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_packagetype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Price'),
        ),
    ]
