# Generated by Django 3.0.8 on 2020-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200723_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address',
            field=models.TextField(default=1, verbose_name='Carteen Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Carteen Name'),
        ),
    ]
