# Generated by Django 2.2 on 2020-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=150, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
    ]
