# Generated by Django 2.2 on 2020-07-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200725_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike', to=settings.AUTH_USER_MODEL),
        ),
    ]
