# Generated by Django 2.2 on 2020-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the food Item you want', verbose_name='Qty.'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Name of The Food', max_length=50, verbose_name='Food Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity of the food Item you want', verbose_name='Qty.'),
        ),
    ]
