# Generated by Django 2.2 on 2020-08-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200731_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processorder',
            name='category',
        ),
    ]
